// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace clinicPractice.Models;

public partial class ClinicSysContext : DbContext
{
    public ClinicSysContext()
    {
    }

    public ClinicSysContext(DbContextOptions<ClinicSysContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Member_EmployeeList> Member_EmployeeLists { get; set; }

    public virtual DbSet<Member_MemberList> Member_MemberLists { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=ClinicSys;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Member_EmployeeList>(entity =>
        {
            entity.HasKey(e => e.Emp_ID).HasName("PK_員工資料表_1");
        });

        modelBuilder.Entity<Member_MemberList>(entity =>
        {
            entity.HasKey(e => e.Member_ID).HasName("PK_會員資料");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}