// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace clinicPractice.Models;

[Table("Member_MemberList")]
public partial class Member_MemberList
{
    [Key]
    public int Member_ID { get; set; }

    public int Member_Number { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public bool? Gender { get; set; }

    [Required]
    [StringLength(50)]
    public string Blood_Type { get; set; }

    [Required]
    [StringLength(50)]
    public string National_ID { get; set; }

    [Required]
    [StringLength(50)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string Contact_Address { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Birth_Date { get; set; }

    [StringLength(50)]
    public string ICE_Name { get; set; }

    [StringLength(50)]
    public string ICE_Number { get; set; }

    [StringLength(50)]
    public string Mem_Password { get; set; }

    [StringLength(50)]
    public string Mem_Email { get; set; }

    public bool? Verification { get; set; }

    [StringLength(50)]
    public string ActivateToken { get; set; }

    public byte[] MemPhoto { get; set; }

    [StringLength(50)]
    public string GoogleSub { get; set; }
}