// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace clinicPractice.Models;

[Table("Member_EmployeeList")]
public partial class Member_EmployeeList
{
    [Key]
    public int Emp_ID { get; set; }

    public int Staff_Number { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public bool? Gender { get; set; }

    [Required]
    [StringLength(50)]
    public string Blood_Type { get; set; }

    [Required]
    [StringLength(50)]
    public string National_ID { get; set; }

    [Required]
    [StringLength(50)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string Contact_Address { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Birth_Date { get; set; }

    [Required]
    [StringLength(50)]
    public string Emp_Type { get; set; }

    [StringLength(50)]
    public string Department { get; set; }

    public string Emp_Password { get; set; }

    public byte[] EmpPhoto { get; set; }

    public bool? Quit { get; set; }

    [StringLength(50)]
    public string EmpMail { get; set; }
}